### PR TITLE
add header to all pages

### PR DESCRIPTION
**Pull request by SlakvichAleksandr**

### CODE REVIEW

**Comment by SlakvichAleksandr** [comment]
https://prnt.sc/qg4kAxWYPGSj
https://prnt.sc/uBTgwl6gGaoN
https://prnt.sc/BrR7jA2NZ0vt

**Review by tatianahutii — CHANGES_REQUESTED** [review]
Need header replace

**Comment by SlakvichAleksandr** [comment]
https://prnt.sc/1HWMPLhC-C__
https://prnt.sc/BM7mTZVML4on
https://prnt.sc/qtqR2wO0t7tl

**Review by tatianahutii — APPROVED** [review]
LGTM

**Pull request merged**
