### PR TITLE
Implemented "Event Details" menu item for new availability backend

### PR DESCRIPTION
**Pull request by Pavliuk13**
changed db schema in README
created new Dtos and changed mapper for creating Availability Slot
changed configuration with relationship between AvailabilitySlot and AdvancedSettings
m-1
m-2

### CODE REVIEW

**Review by tatianahutii — CHANGES_REQUESTED** [review]
Everything looks good
But could you please fix git warnings?

**Comment by Pavliuk13** [comment]
> Everything looks good But could you please fix git warnings?

fixed

**Comment by tatianahutii** [comment]
You need to recreate your migration

**Comment by Pavliuk13** [comment]
> You need to recreate your migration

can I delete 2 last migrations (ChangeAvailabilitySlotAndSettings and PerformUserProperty) and create one migration with all those changes ?

**Comment by Pavliuk13** [comment]
> You need to recreate your migration

done

**Review by tatianahutii — APPROVED** [review]
LGTM

**Pull request merged**
